[package]
name = "mir9cc"
version = "0.1.0"
authors = ["masashi <ym.atonement.oy999@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4.0"